#ifndef OBJ_PROCESSOR_FACE_HIDDING
#define OBJ_PROCESSOR_FACE_HIDDING

#include "obj_processor.h"

#include "obj_processor_face_hidding.h"

void obj_processor_hide_back_faces(obj_processor_three_dimensions_model *model, obj_processor_three_dimensions_model_vertex *projected_vertices);

obj_processor_three_dimensions_model_vertex *obj_processor_get_normal_vector(obj_processor_three_dimensions_model_face *face, obj_processor_three_dimensions_model_vertex *projected_vertices);

obj_processor_three_dimensions_model_vertex *obj_processor_vector_substraction(obj_processor_three_dimensions_model_vertex *minuend, obj_processor_three_dimensions_model_vertex *substranting);

obj_processor_three_dimensions_model_vertex *obj_processor_cross_product(obj_processor_three_dimensions_model_vertex *vector_a, obj_processor_three_dimensions_model_vertex *vector_b);

#endif